Repository scanoss/scanoss.py, pull requests merged in 2025-03, with the labels that each got.

#105 chore: update dockerfile to use python 3.10-slim
  CHANGELOG.md
  Dockerfile
  src/scanoss/__init__.py
Labels: enhancement

#107 Bug/jortiz/spdxlite output
  CHANGELOG.md
  src/scanoss/__init__.py
  src/scanoss/spdxlite.py
Labels: bug

#108 fix: SP-2195 timeout error during dependency scan
  CHANGELOG.md
  src/scanoss/scanossgrpc.py
Labels: bug, enhancement
